### ISSUE TITLE
latest tag is not multiarchitecture

### ISSUE THREAD

**Issue by iloveitaly** [webdevops/go-crond#30]
Not sure why, but only one architecture is available under the `latest` tag

**Comment by mblaschke** [comment]
i've updated the build system and this issue is till not fixed for Docker Hub.
I'm wondering because the same image is pushed in the exactly same run also to Quay which is being pushed as multi arch image.

I've retried the jobs and now it's available as multi arch image but I think it's a Docker Hub issue here (but I've never seen such an issue).
